apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "02-react.fullname" . }}
  labels:
    {{- include "02-react.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "02-react.selectorLabels" . | nindent 6 }}
