{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "30-ws-elixir.serviceAccountName" . }}
  labels:
    {{- include "30-ws-elixir.labels" . | nindent 4 }}
{{- end }}
