{{- if ge (int .Values.replicaCount) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "13-workbox.fullname" . }}
  labels:
    {{- include "13-workbox.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "13-workbox.selectorLabels" . | nindent 6 }}
{{- end }}
