{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "13-workbox.serviceAccountName" . }}
  labels:
    {{- include "13-workbox.labels" . | nindent 4 }}
{{- end }}
