apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "01-sveltekit.fullname" . }}
  labels:
    {{- include "01-sveltekit.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "01-sveltekit.selectorLabels" . | nindent 6 }}
