apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "25-play.fullname" . }}
  labels:
    {{- include "25-play.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "25-play.selectorLabels" . | nindent 6 }}
