{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "29-spring-graphql.serviceAccountName" . }}
  labels:
    {{- include "29-spring-graphql.labels" . | nindent 4 }}
{{- end }}
