{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "15-fastapi.serviceAccountName" . }}
  labels:
    {{- include "15-fastapi.labels" . | nindent 4 }}
{{- end }}
