app:
  title: Pipeline Studio
  baseUrl: http://localhost:3000

organization:
  name: Yarova

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  ### Example of a proxy endpoint for internal tooling
  # '/test':
  #   target: 'https://example.com'
  #   changeOrigin: true

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Domain]
  locations:
    - type: url
      target: https://github.com/yarova-ca/pipeline-studio/blob/main/backstage/catalog/all.yaml
      rules:
        - allow: [Location]

    # Org structure
    - type: url
      target: https://github.com/yarova-ca/pipeline-studio/blob/main/backstage/org/users.yaml
      rules:
        - allow: [User, Group]

    # Scaffolder templates
    - type: url
      target: https://github.com/yarova-ca/pipeline-studio/blob/main/backstage/templates/backend-service/template.yaml
      rules:
        - allow: [Template]

    - type: url
      target: https://github.com/yarova-ca/pipeline-studio/blob/main/backstage/templates/frontend-spa/template.yaml
      rules:
        - allow: [Template]

    - type: url
      target: https://github.com/yarova-ca/pipeline-studio/blob/main/backstage/templates/grpc-service/template.yaml
      rules:
        - allow: [Template]

    # Root system entity
    - type: url
      target: https://github.com/yarova-ca/pipeline-studio/blob/main/catalog-info.yaml
      rules:
        - allow: [System, Domain]

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

scaffolder:
  defaultAuthor:
    name: Yarova Platform Bot
    email: rohith@yarova.ca
  defaultCommitMessage: "Initialize service from pipeline-studio template"

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: localKubectlProxy

search:
  pg:
    highlightOptions:
      useHighlight: true
      maxWord: 35
      minWord: 15
      shortWord: 3
      highlightAll: false
      maxFragments: 10
      fragmentDelimiter: ' ... '
