apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
images:
  - name: ghcr.io/yarova-ca/07-nextjs-app-router
    newTag: "latest"
patches:
  - target:
      kind: Deployment
      name: 07-nextjs-app-router
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
