{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "15-starlette.serviceAccountName" . }}
  labels:
    {{- include "15-starlette.labels" . | nindent 4 }}
{{- end }}
