{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "07-remix.serviceAccountName" . }}
  labels:
    {{- include "07-remix.labels" . | nindent 4 }}
{{- end }}
