apiVersion: apps/v1
kind: Deployment
metadata:
  name: 15-fastapi
  labels:
    app: 15-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 15-fastapi
  template:
    metadata:
      labels:
        app: 15-fastapi
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: 15-fastapi
          image: ghcr.io/yarova-ca/15-fastapi:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
