{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "30-ws-ruby.serviceAccountName" . }}
  labels:
    {{- include "30-ws-ruby.labels" . | nindent 4 }}
{{- end }}
