apiVersion: apps/v1
kind: Deployment
metadata:
  name: 27-crow
  labels:
    app: 27-crow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 27-crow
  template:
    metadata:
      labels:
        app: 27-crow
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: 27-crow
          image: ghcr.io/yarova-ca/27-crow:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
