apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "29-hot-chocolate.fullname" . }}
  labels:
    {{- include "29-hot-chocolate.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "29-hot-chocolate.selectorLabels" . | nindent 6 }}
