{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "29-hot-chocolate.serviceAccountName" . }}
  labels:
    {{- include "29-hot-chocolate.labels" . | nindent 4 }}
{{- end }}
