apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    app.kubernetes.io/part-of: pipeline-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    kubernetes.io/metadata.name: dev
    pod.security.kubernetes.io/enforce: baseline
    pod.security.kubernetes.io/warn: baseline
    pod.security.kubernetes.io/audit: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    kubernetes.io/metadata.name: staging
    pod.security.kubernetes.io/enforce: baseline
    pod.security.kubernetes.io/warn: baseline
    pod.security.kubernetes.io/audit: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    kubernetes.io/metadata.name: prod
    pod.security.kubernetes.io/enforce: restricted
    pod.security.kubernetes.io/warn: restricted
    pod.security.kubernetes.io/audit: restricted
