apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "28-python-grpc.fullname" . }}
  labels:
    {{- include "28-python-grpc.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "28-python-grpc.selectorLabels" . | nindent 6 }}
