// Security + DevOps glossary — every term defined plainly.
// No prior knowledge assumed. 52 terms.
// Used by: ReferenceTabs Glossary tab, stage detail linkify.

export interface GlossaryTerm {
  term: string;
  full: string;
  def: string;
}

export const GLOSSARY: GlossaryTerm[] = [
  { term: 'SBOM',           full: 'Software Bill of Materials',                def: 'A machine-readable inventory of every library, OS package, and dependency inside a container image. Like an ingredients list for software.' },
  { term: 'SLSA',           full: 'Supply chain Levels for Software Artifacts', def: 'A security framework defining integrity levels for the build process. Level 3 requires an isolated build job with signed provenance. Pronounced "salsa".' },
  { term: 'DAST',           full: 'Dynamic Application Security Testing',       def: 'A scanner that attacks your running application like an external attacker. Sends malicious HTTP inputs and checks for vulnerable responses. OWASP ZAP is the most common open-source DAST tool.' },
  { term: 'SAST',           full: 'Static Application Security Testing',        def: 'A scanner that reads source code without running it to find security bug patterns. Semgrep and CodeQL are examples. Catches injection, hardcoded secrets, OWASP Top 10.' },
  { term: 'SCA',            full: 'Software Composition Analysis',              def: 'Scans package manifests (package.json, go.mod, requirements.txt) for known CVEs in open-source dependencies. The "dependency audit" category of security scanning.' },
  { term: 'IaC Scan',       full: 'Infrastructure-as-Code Scan',                def: 'Scans Dockerfile, Kubernetes YAML, and Terraform files for security misconfigurations. Checkov is the most common open-source tool. Maps findings to CIS benchmarks.' },
  { term: 'CVE',            full: 'Common Vulnerabilities and Exposures',        def: 'A public database entry for a known security vulnerability. Format: CVE-YEAR-NUMBER. Severity rated by CVSS score. CRITICAL = 9.0+, HIGH = 7.0–8.9, MEDIUM = 4.0–6.9.' },
  { term: 'CVSS',           full: 'Common Vulnerability Scoring System',         def: 'A 0–10 score for vulnerability severity. CRITICAL ≥9.0. HIGH 7.0–8.9. MEDIUM 4.0–6.9. LOW 0.1–3.9. Informational = 0.' },
  { term: 'distroless',     full: '',                                            def: 'A minimal container base image containing only the application runtime — no shell, no package manager, no OS tools. Created by Google. Dramatically smaller attack surface than Alpine or Debian.' },
  { term: 'cosign',         full: '',                                            def: "A tool from the Sigstore project that signs container images using the CI job's OIDC identity. No private key is stored anywhere. Signing key derived from the short-lived CI identity token." },
  { term: 'keyless signing', full: '',                                           def: 'Signing without a stored private key. The signing key is derived from a short-lived OIDC identity token. The key exists only for the duration of the signing operation — nothing persists.' },
  { term: 'Sigstore',       full: '',                                            def: 'An open-source project providing free infrastructure for signing software artifacts. Components: cosign (signing tool), Rekor (transparency log), Fulcio (certificate authority for OIDC-based certs).' },
  { term: 'Rekor',          full: '',                                            def: 'A public, append-only transparency log for software signing events. Every cosign signing operation creates an immutable entry. Anyone can verify when and how an artifact was signed.' },
  { term: 'OIDC',           full: 'OpenID Connect',                              def: 'An authentication protocol that lets a service (like a CI runner) prove its identity without a stored password. The CI provider issues a short-lived signed token that the registry IAM policy trusts.' },
  { term: 'SARIF',          full: 'Static Analysis Results Interchange Format',  def: 'A JSON standard for reporting security scan results. GitHub Security tab reads SARIF files natively. Every scanner in this pipeline outputs SARIF format.' },
  { term: 'SPDX',           full: 'Software Package Data Exchange',              def: 'An ISO standard for describing software packages and their licenses. SPDX-JSON is the machine-readable format used for SBOMs in this pipeline. Each package gets an SPDX license identifier.' },
  { term: 'PURL',           full: 'Package URL',                                 def: 'A standard identifier for software packages across all ecosystems. Format: pkg:TYPE/NAMESPACE/NAME@VERSION. Example: pkg:npm/%40angular/core@17.0.0. Used in SBOMs.' },
  { term: 'OSV',            full: 'Open Source Vulnerabilities',                 def: 'A vulnerability database for open-source software, maintained by Google. More comprehensive for open-source than NVD alone. Used by Trivy and dependency-review-action.' },
  { term: 'NVD',            full: 'National Vulnerability Database',             def: "NIST's database of all known CVEs. The traditional authoritative source of vulnerability data. Updated within days of CVE publication. Used by Trivy." },
  { term: 'multi-stage build', full: '',                                         def: 'A Dockerfile pattern with multiple FROM stages. The builder stage compiles the code. The runtime stage copies only the compiled output — discarding all build tools. Result: smaller, more secure final image.' },
  { term: 'pre-commit',     full: '',                                            def: 'A framework for managing and running git commit hooks. The same hooks run locally (before each commit) and in CI (to catch --no-verify bypasses). Hook list stored in .pre-commit-config.yaml.' },
  { term: 'admission control', full: '',                                         def: 'A Kubernetes mechanism that intercepts API requests before they are persisted. Kyverno and OPA Gatekeeper act as admission controllers to enforce policies at pod deploy time.' },
  { term: 'Kyverno',        full: '',                                            def: 'A Kubernetes policy engine that enforces rules at pod admission. Used in this pipeline to verify cosign signatures before any pod starts. Configured as fail-closed (I-20).' },
  { term: 'canary rollout', full: '',                                            def: 'A deployment pattern where new code receives a small % of traffic (e.g., 5%) while the rest stays on old code. Traffic shifts to 100% if error rate stays low. Rolls back automatically if error rate spikes.' },
  { term: 'OWASP Top 10',  full: '',                                             def: 'The 10 most critical web application security risks, published annually by OWASP. Includes injection, broken access control, XSS, cryptographic failures. SAST tools check code for these patterns.' },
  { term: 'Semgrep',        full: '',                                            def: 'A fast open-source SAST tool that matches code patterns using rule files written in YAML. 1200+ security rules available. Used in S3 for OWASP Top-10 scanning across all language stacks.' },
  { term: 'Trivy',          full: '',                                            def: 'An open-source vulnerability scanner by Aqua Security. Scans container images, SBOMs, and filesystems for CVEs. Supports SARIF output. Default tool for container scanning in this pipeline.' },
  { term: 'Checkov',        full: '',                                            def: 'An open-source IaC scanner by Bridgecrew. Checks Dockerfile, K8s YAML, Terraform against 2000+ security rules. Maps every finding to a CIS benchmark or CVE identifier.' },
  { term: 'Gitleaks',       full: '',                                            def: 'An open-source secret scanner. Detects API keys, passwords, private keys in git history and staged files using regex patterns for 150+ secret types. Runs in pre-commit and in CI.' },
  { term: 'FOSSA',          full: '',                                            def: 'A commercial license compliance tool. Scans dependency trees to detect open-source licenses conflicting with commercial use. Used in S3b. Blocks GPL/AGPL in commercial projects.' },
  { term: 'Syft',           full: '',                                            def: 'An open-source SBOM generator by Anchore. Reads container images and filesystems, identifies every package, and produces SBOMs in SPDX-JSON or CycloneDX format. Used in S8a.' },
  { term: 'k6',             full: '',                                            def: 'An open-source load testing tool written in Go. Test scripts are written in JavaScript. Measures p50/p95/p99 latency, throughput (req/s), and error rate under simulated concurrent load.' },
  { term: 'ZAP',            full: 'Zed Attack Proxy',                            def: "OWASP's open-source DAST tool. Automatically spiders web application endpoints and attacks them with injection payloads, authentication manipulation, and malformed inputs." },
  { term: 'Falco',          full: '',                                            def: 'An open-source runtime security tool. Uses eBPF to monitor syscalls inside running containers. Alerts when containers do unexpected things: spawn shells, write outside expected paths, make unusual network connections.' },
  { term: 'eBPF',           full: 'Extended Berkeley Packet Filter',             def: 'A Linux kernel technology that runs sandboxed programs in the kernel for observability and security. Falco uses it to monitor container syscalls without modifying the kernel or containers.' },
  { term: 'Codecov',        full: '',                                            def: 'A code coverage reporting service. Tracks test coverage percentage over time and comments on PRs when coverage decreases. Enforces Invariant I-9.' },
  { term: 'Dependabot',     full: '',                                            def: 'A GitHub service that automatically creates PRs to update outdated dependencies. Paired with branch protection (I-15), it keeps CVE counts low without manual effort.' },
  { term: 'Renovate',       full: '',                                            def: 'An open-source alternative to Dependabot. Supports more package managers and more configuration options. Creates automatic update PRs for dependencies and GitHub Actions versions.' },
  { term: 'SLSA provenance', full: '',                                           def: "A signed statement recording: this artifact (identified by digest) was built from this source commit, by this builder, using these exact steps. Cannot be forged without the CI provider's signing key." },
  { term: 'CSR',            full: 'Client-Side Rendering',                       def: 'All HTML is built in the browser using JavaScript. The server returns an empty shell HTML + JS bundle. Frameworks: React SPA, Vue + Vite, Angular. Runtime image: nginx (static file server, no Node.js). Port: 80.' },
  { term: 'SSR',            full: 'Server-Side Rendering',                       def: 'HTML is built on the server on every request. The server runs JavaScript to produce HTML before sending to the browser. Frameworks: Remix, SvelteKit. Runtime image: Node.js or distroless/nodejs. Port: 3000+.' },
  { term: 'SSG',            full: 'Static Site Generation',                      def: 'HTML is built at CI build time, not at request time. The server returns pre-built HTML files. Frameworks: Gatsby, Astro (default). Runtime image: nginx. Port: 80. No server attack surface at runtime.' },
  { term: 'ISR',            full: 'Incremental Static Regeneration',             def: 'Next.js feature. Pages are pre-built at build time (SSG), then re-generated in the background after a revalidation period. Combines SSG speed with near-real-time content updates. Requires a running Node.js server.' },
  { term: 'attestation',    full: '',                                            def: 'A cryptographic statement attached to a container image in the registry. Created by cosign. Contains machine-readable data (like an SBOM or SLSA provenance) plus a signature that proves the CI system produced it. Stored as OCI artifact (.att suffix).' },
  { term: 'in-toto',        full: '',                                            def: 'The standard file format for SLSA provenance attestations. File extension: .intoto.jsonl. Contains a signed envelope with: builder identity, source commit, build steps, and output digest. Verifiable with slsa-verifier.' },
  { term: 'multi-arch',     full: '',                                            def: 'A container image that contains binaries for multiple CPU architectures (linux/amd64 + linux/arm64). Built with docker buildx --platform. Required when deploying to ARM nodes (AWS Graviton, Apple Silicon dev machines).' },
  { term: 'buildx',         full: '',                                            def: 'Docker CLI plugin that extends docker build with multi-platform support, layer cache export, and BuildKit features. Required for linux/amd64 + linux/arm64 cross-compilation in CI. Enabled by docker/setup-buildx-action@v3.' },
  { term: 'QEMU',           full: 'Quick Emulator',                              def: 'A processor emulator used in multi-arch builds to run ARM binaries on amd64 CI runners. Required when cross-compiling languages that do not support native cross-compilation (non-Go). Installed by docker/setup-qemu-action@v3.' },
  { term: 'AST',            full: 'Abstract Syntax Tree',                        def: 'A tree representation of source code structure used by SAST tools. Semgrep parses code into ASTs to apply pattern-matching security rules without executing the code.' },
  { term: 'fetch-depth:0',  full: '',                                            def: 'A Git checkout option that fetches the full commit history instead of only the latest commit. Required by Gitleaks to scan all historical commits for leaked secrets.' },
  { term: 'Argo Rollouts',  full: '',                                            def: 'A Kubernetes controller that extends Deployments with canary, blue-green, and analysis-based promotion. Used in Phase 4 for progressive delivery with automatic error-rate rollback.' },
  { term: 'Flux',           full: '',                                            def: 'A GitOps tool by Weaveworks. Continuously syncs cluster state to match a git repository. Pulls changes (vs ArgoCD push). Supports Kustomize and Helm. CNCF graduated.' },
];
