// industries.ts — Industry vertical definitions with compliance, SLA, and data-sensitivity profiles.
// Extracted from v1 index.html: INDUSTRIES (line 8332).
// Source guidance: industry analyst guidance + sector regulators (HHS, FFIEC, FedRAMP).
// Used by: industry dropdown autolink + industry context block.

import type { IndustryDef } from './types';

export const INDUSTRIES: Record<string, IndustryDef> = {
  none: {
    label: 'General SaaS',
    suggestedCompliance: 'soc2',
    sla: '99.9%',
    traffic: 'Internet-facing',
    sensitivity: 'Customer credentials + business data',
    note: 'Default profile. Tune compliance as customer contracts demand.',
  },
  fintech: {
    label: 'Fintech / Payments',
    suggestedCompliance: 'pci',
    suggestedCompliance2: 'soc2',
    sla: '99.95%',
    traffic: 'Internet-facing + partner APIs',
    sensitivity: 'PAN (Primary Account Number) + customer KYC',
    note: 'PCI-DSS scope split: CDE workloads need quarterly ASV scans + segmentation evidence.',
  },
  healthcare: {
    label: 'Healthcare / Health-tech',
    suggestedCompliance: 'hipaa',
    suggestedCompliance2: 'soc2',
    sla: '99.95%',
    traffic: 'Provider portals + patient APIs',
    sensitivity: 'PHI (Protected Health Information)',
    note: 'BAA (Business Associate Agreement) required with every downstream processor. HIPAA breach notification rules apply.',
  },
  government: {
    label: 'Government / Public Sector',
    suggestedCompliance: 'fedramp',
    sla: '99.99%',
    traffic: 'Authenticated agency users only',
    sensitivity: 'CUI (Controlled Unclassified Information)',
    note: 'FedRAMP Moderate baseline. Continuous monitoring + JAB authorization or 3PAO sponsor required.',
  },
  defense: {
    label: 'Defense / Aerospace',
    suggestedCompliance: 'cmmc',
    suggestedCompliance2: 'fedramp',
    sla: '99.99%',
    traffic: 'Closed network / VPN only',
    sensitivity: 'CUI + ITAR controlled tech data',
    note: 'CMMC Level 2+ + DFARS 252.204-7012 + supply-chain provenance mandatory.',
  },
  retail: {
    label: 'Retail / E-commerce',
    suggestedCompliance: 'pci',
    suggestedCompliance2: 'soc2',
    sla: '99.95%',
    traffic: 'Peak-driven (Black Friday)',
    sensitivity: 'PAN + browsing behavior + loyalty data',
    note: 'PCI scope on checkout path. Bot-mitigation outside pipeline (Cloudflare/Akamai).',
  },
  media: {
    label: 'Media / Publishing',
    suggestedCompliance: 'gdpr',
    suggestedCompliance2: 'soc2',
    sla: '99.9%',
    traffic: 'High read, low write',
    sensitivity: 'Subscriber PII + viewing analytics',
    note: 'GDPR Article 30 records of processing. CDN cache invalidation needs auditable controls.',
  },
  iot: {
    label: 'IoT / Edge',
    suggestedCompliance: 'soc2',
    suggestedCompliance2: 'iso27001',
    sla: '99.0% (edge tolerated)',
    traffic: 'Device fleets + MQTT/CoAP',
    sensitivity: 'Device identity + telemetry',
    note: 'Image signing extends to firmware. Edge nodes cannot run full Falco — use lightweight Tetragon.',
  },
  education: {
    label: 'Education / EdTech',
    suggestedCompliance: 'ferpa',
    sla: '99.9%',
    traffic: 'Student portals + admin tools',
    sensitivity: 'FERPA student records',
    note: 'FERPA + COPPA (under 13) overlap. Data-residency per state regulator.',
  },
  energy: {
    label: 'Energy / Utilities',
    suggestedCompliance: 'nerccip',
    suggestedCompliance2: 'iso27001',
    sla: '99.99%',
    traffic: 'Operator consoles + SCADA gateways',
    sensitivity: 'Critical infrastructure',
    note: 'NERC CIP for bulk-electric. Air-gap reviews for OT (Operational Technology) boundaries.',
  },
  ai: {
    label: 'AI / ML Platforms',
    suggestedCompliance: 'iso27001',
    suggestedCompliance2: 'soc2',
    sla: '99.95%',
    traffic: 'API + GPU job runners',
    sensitivity: 'Training data + model weights',
    note: 'Add model SBOM + provenance. Track GPU image signatures separately.',
  },
};
