// Local dev hook file generators.
// Generates: .pre-commit-config.yaml, .gitleaks.toml, .trivyignore, .checkov.yaml, sbom-policy.yaml

import type { PipelineConfig } from '../lib/types';
import { TV } from '../lib/tools';

function langExtras(cfg: PipelineConfig): string {
  const be = cfg.beKey;
  const fe = cfg.feKey;
  const lines: string[] = [];

  if (fe.includes('react') || fe.includes('vue') || fe.includes('angular') || fe.includes('svelte') || fe.includes('next') || fe.includes('remix') || fe.includes('nuxt')) {
    lines.push(`  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.16.0
    hooks:
      - id: eslint
        files: \\.[jt]sx?$
        types: [file]`);
  }

  if (be.includes('python') || fe.includes('python')) {
    lines.push(`  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
      - id: ruff-format`);
  }

  if (be.includes('go-')) {
    lines.push(`  - repo: https://github.com/golangci/golangci-lint
    rev: v1.62.0
    hooks:
      - id: golangci-lint`);
  }

  if (be.includes('rust-')) {
    lines.push(`  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]`);
  }

  return lines.join('\n');
}

export function generatePreCommitConfig(cfg: PipelineConfig): string {
  const extras = langExtras(cfg);
  return `# .pre-commit-config.yaml
# Generated by DevSecOps Pipeline Studio — 2026-05-24
# Run locally: pre-commit run --all-files
# Install: pip install pre-commit && pre-commit install
# Same hooks run in CI (S1) to catch --no-verify bypasses.

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: ${TV.gitleaksImage.replace('zricethezav/gitleaks:', '')}
    hooks:
      - id: gitleaks

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        args: [--failure-threshold, error]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: [--maxkb=500]
${extras}
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.405
    hooks:
      - id: checkov
        args: [--quiet, --compact]
`;
}

export function generateGitleaksConfig(_cfg: PipelineConfig): string {
  return `# .gitleaks.toml
# Generated by DevSecOps Pipeline Studio — 2026-05-24
# Allowlist: add repo-specific patterns below.
# Never add real secrets — only patterns for known false-positives.
# Reference: https://github.com/gitleaks/gitleaks

title = "gitleaks config"

[allowlist]
  description = "Repo-specific allowlist"
  regexTarget = "match"
  # Example: test fixture secrets (never real)
  # regexes = ["EXAMPLE_TEST_SECRET"]
  paths = [
    '''.gitleaks.toml''',
    '''tests/fixtures/''',
    '''testdata/''',
  ]

# Policy: no secret type is exempt by default.
# If a finding is a false-positive, add it here with a comment explaining why.
# All allowlist changes require a second reviewer approval per I-2.
`;
}

export function generateTrivyIgnore(_cfg: PipelineConfig): string {
  return `# .trivyignore
# Generated by DevSecOps Pipeline Studio — 2026-05-24
# Policy: suppress a CVE only when ALL three conditions are met:
#   1. The CVE has no fix available from upstream.
#   2. The CVE has been reviewed by your security team.
#   3. An expiry date is set (max 90 days — I-19).
#
# Format: CVE-ID [expiry:YYYY-MM-DD] # Reviewer: name / Reason: one-line
#
# Example (uncomment and edit):
# CVE-2024-12345 exp:2026-08-24 # Reviewer: jane / Reason: no fix, base image risk accepted
#
# All suppressions require a PR review by a team member with security approval.
# Suppressions without an expiry date are rejected by the pipeline.
`;
}

export function generateCheckovConfig(_cfg: PipelineConfig): string {
  return `# .checkov.yaml
# Generated by DevSecOps Pipeline Studio — 2026-05-24
# Checkov IaC scanner configuration.
# Reference: https://www.checkov.io/5.Policy%20Index/all.html

quiet: true
compact: true
output: cli

# Checks to skip — only skip with documented justification.
# Policy: same conditions as .trivyignore (no fix + security team review + expiry comment).
skip-check:
  # Example: CKV_DOCKER_2 - Healthcheck in Dockerfile
  # Skipped because: healthcheck managed externally by Kubernetes probes (readinessProbe/livenessProbe).
  - CKV_DOCKER_2

# Soft-fail: do not block CI on informational findings.
# Remove this if you want to gate on everything.
soft-fail-on:
  - LOW
`;
}

export function generateSbomPolicy(_cfg: PipelineConfig): string {
  return `# sbom-policy.yaml
# Generated by DevSecOps Pipeline Studio — 2026-05-24
# Kyverno ClusterPolicy: enforce image signing + SBOM attestation before any pod starts.
# Prerequisites: Kyverno installed in cluster, cosign public key or keyless configured.
# Invariant: I-20 (admission gate — no unsigned image reaches prod).
# Reference: https://kyverno.io/policies/other/verify-image/verify-image/

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature
  annotations:
    policies.kyverno.io/title: Verify Image Signature + SBOM
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Requires all images to be signed by cosign (keyless, Sigstore Rekor transparency log).
      Requires SBOM attestation to be present. Blocks unsigned/unattested images at admission.
      Enforces Invariant I-20.
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-image-signature
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: ["default", "production", "staging"]
      verifyImages:
        - imageReferences: ["*"]
          attestors:
            - count: 1
              entries:
                - keyless:
                    subject: "https://github.com/*"
                    issuer: "https://token.actions.githubusercontent.com"
                    rekor:
                      url: https://rekor.sigstore.dev
          attestations:
            - predicateType: https://spdx.dev/Document
              conditions:
                - all:
                    - key: "{{ spdxVersion }}"
                      operator: NotEquals
                      value: ""
`;
}
