// Helm values file generators — dev, staging, production environments.

import type { PipelineConfig } from '../lib/types';

export function generateHelmValues(cfg: PipelineConfig, env: 'dev' | 'staging' | 'prod'): string {
  const app = cfg.appName ?? 'myapp';
  const port = cfg.port ?? 3000;
  const healthPath = cfg.healthPath ?? '/health';

  const envConfigs = {
    dev: {
      replicas: 1,
      cpuRequest: '50m',
      cpuLimit: '200m',
      memRequest: '64Mi',
      memLimit: '256Mi',
      tag: 'dev-latest',
      ingress: false,
    },
    staging: {
      replicas: 3,
      cpuRequest: '100m',
      cpuLimit: '500m',
      memRequest: '128Mi',
      memLimit: '512Mi',
      tag: 'staging-latest',
      ingress: true,
    },
    prod: {
      replicas: 10,
      cpuRequest: '250m',
      cpuLimit: '1000m',
      memRequest: '256Mi',
      memLimit: '1Gi',
      tag: 'latest',
      ingress: true,
    },
  };

  const c = envConfigs[env];

  return `# deploy/charts/${app}/values-${env}.yaml
# Generated by DevSecOps Pipeline Studio — 2026-05-24
# Environment: ${env.toUpperCase()}

replicaCount: ${c.replicas}

image:
  repository: ${app}
  tag: "${c.tag}"   # Patched by CI: helm upgrade --set image.tag=<sha>
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: ${port}

resources:
  requests:
    cpu: "${c.cpuRequest}"
    memory: "${c.memRequest}"
  limits:
    cpu: "${c.cpuLimit}"
    memory: "${c.memLimit}"

# Security: enforce non-root at Helm level (redundant with Kyverno — defense in depth).
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

probes:
  readiness:
    path: ${healthPath}
    port: ${port}
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: ${healthPath}
    port: ${port}
    initialDelaySeconds: 15
    periodSeconds: 20
${c.ingress ? `
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: ${app}-${env}.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ${app}-${env}-tls
      hosts:
        - ${app}-${env}.example.com
` : `
ingress:
  enabled: false
`}${env === 'prod' ? `
# Production: PodDisruptionBudget prevents full outage during rolling updates.
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Production: HorizontalPodAutoscaler scales on CPU.
autoscaling:
  enabled: true
  minReplicas: ${c.replicas}
  maxReplicas: ${c.replicas * 3}
  targetCPUUtilizationPercentage: 70
` : ''}`;
}
