// Kustomize deploy tree generator.
// Generates: base/deployment.yaml, base/kustomization.yaml, overlays per env.

import type { PipelineConfig } from '../lib/types';

export function generateDockerIgnore(_cfg: PipelineConfig): string {
  return `# .dockerignore
# Generated by DevSecOps Pipeline Studio — 2026-05-24
# Keeps build context small and avoids leaking sensitive files into the image.

# VCS
.git
.gitignore
.gitattributes

# Dev tooling
node_modules
.pnp
.pnp.js
.yarn/cache
.yarn/unplugged

# Build artifacts
dist
build
.next
.nuxt
out
coverage
.turbo

# Tests — never in production image
__tests__
*.test.ts
*.test.js
*.spec.ts
*.spec.js
e2e
playwright-report

# Secrets + env — never in production image
.env
.env.*
*.pem
*.key
*.p12
*.pfx
secrets/

# Docs + CI metadata
*.md
README*
CHANGELOG*
CONTRIBUTING*
.github
.gitlab
Jenkinsfile
azure-pipelines.yml

# Tooling configs that don't affect runtime
.eslintrc*
.prettierrc*
.pre-commit-config.yaml
.gitleaks.toml
.trivyignore
.checkov.yaml
tsconfig*.json
`;
}

export function generateBaseDeployment(cfg: PipelineConfig): string {
  const app = cfg.appName ?? 'myapp';
  const port = cfg.port ?? 3000;
  const healthPath = cfg.healthPath ?? '/health';
  return `# deploy/base/deployment.yaml
# Generated by DevSecOps Pipeline Studio — 2026-05-24
# Security: non-root, read-only root filesystem, no privilege escalation.
# Image digest pinned at deploy time by ArgoCD/Flux (kustomize edit set image).

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app}
  labels:
    app: ${app}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${app}
  template:
    metadata:
      labels:
        app: ${app}
      annotations:
        # cosign verify-image runs as a Kyverno policy at admission — see sbom-policy.yaml
        policy.sigstore.dev/include: "true"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ${app}
          image: ${app}:latest   # Kustomize patches this with digest at deploy time
          ports:
            - containerPort: ${port}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          readinessProbe:
            httpGet:
              path: ${healthPath}
              port: ${port}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: ${healthPath}
              port: ${port}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${app}
spec:
  selector:
    app: ${app}
  ports:
    - port: 80
      targetPort: ${port}
`;
}

export function generateBaseKustomization(cfg: PipelineConfig): string {
  const app = cfg.appName ?? 'myapp';
  return `# deploy/base/kustomization.yaml
# Generated by DevSecOps Pipeline Studio — 2026-05-24

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ${app}-base

resources:
  - deployment.yaml

images:
  - name: ${app}
    newTag: latest   # Patched by CI: kustomize edit set image ${app}=<registry>/<image>@sha256:<digest>
`;
}

export function generateOverlayKustomization(cfg: PipelineConfig, env: 'dev' | 'test' | 'staging' | 'prod'): string {
  const app = cfg.appName ?? 'myapp';
  const replicas = { dev: 1, test: 2, staging: 3, prod: 10 }[env];
  const namespace = env === 'prod' ? 'production' : env;
  return `# deploy/overlays/${env}/kustomization.yaml
# Generated by DevSecOps Pipeline Studio — 2026-05-24

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ${app}-${env}

namespace: ${namespace}

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${app}
      spec:
        replicas: ${replicas}
    target:
      kind: Deployment
      name: ${app}
`;
}
