{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "25-http4s.serviceAccountName" . }}
  labels:
    {{- include "25-http4s.labels" . | nindent 4 }}
{{- end }}
