apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "04-astro.fullname" . }}
  labels:
    {{- include "04-astro.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "04-astro.selectorLabels" . | nindent 6 }}
