replicaCount: 1

image:
  repository: "ghcr.io/yarova-ca/29-spring-graphql"   # set in CI: ghcr.io/yarova-ca/29-spring-graphql
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: "29-spring-graphql"

serviceAccount:
  create: true
  name: "29-spring-graphql"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: 29-spring-graphql.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env: {}

envFrom: []

livenessProbe:
  httpGet:
    path: /health/live
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

networkPolicy:
  enabled: false
