{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "05-qwik.serviceAccountName" . }}
  labels:
    {{- include "05-qwik.labels" . | nindent 4 }}
{{- end }}
