apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "20-actix-web.fullname" . }}
  labels:
    {{- include "20-actix-web.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "20-actix-web.selectorLabels" . | nindent 6 }}
