apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "13-vite-pwa.fullname" . }}
  labels:
    {{- include "13-vite-pwa.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "13-vite-pwa.selectorLabels" . | nindent 6 }}
