apiVersion: apps/v1
kind: Deployment
metadata:
  name: 01-nextjs
  labels:
    app: 01-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 01-nextjs
  template:
    metadata:
      labels:
        app: 01-nextjs
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: 01-nextjs
          image: ghcr.io/yarova-ca/01-nextjs:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
