replicaCount: 3
image:
  tag: "latest"
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
ingress:
  enabled: true
  hosts:
    - host: 29-graphql-ruby.yarova.ca
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: 29-graphql-ruby-tls
      hosts:
        - 29-graphql-ruby.yarova.ca
