source 'https://rubygems.org'
ruby '3.3.0'

gem 'sinatra',        '~> 4.0'
gem 'rackup',         '~> 2.1'
gem 'puma',           '~> 6.4'
gem 'dotenv',         '~> 3.1'
# JWT
gem 'jwt',            '~> 2.8'
# ORM — Sequel with PostgreSQL adapter
gem 'sequel',         '~> 5.80'
gem 'pg',             '~> 1.5'
# SQLite for dev / test (no Postgres needed)
gem 'sqlite3',        '~> 1.7'

group :test do
  gem 'rspec',        '~> 3.13'
  gem 'rack-test',    '~> 2.1'
end
