apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: ghcr.io/yarova-ca/03-hugo
    newTag: "dev"
patches:
  - target:
      kind: Deployment
      name: 03-hugo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
