apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
images:
  - name: ghcr.io/yarova-ca/25-http4s
    newTag: "staging"
patches:
  - target:
      kind: Deployment
      name: 25-http4s
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
