micronaut.server.port=8080
endpoints.all.sensitive=false
micronaut.metrics.enabled=true
micronaut.metrics.export.prometheus.enabled=true
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false
