apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "27-crow.fullname" . }}
  labels:
    {{- include "27-crow.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "27-crow.selectorLabels" . | nindent 6 }}
