{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "27-crow.serviceAccountName" . }}
  labels:
    {{- include "27-crow.labels" . | nindent 4 }}
{{- end }}
