source 'https://rubygems.org'
ruby '3.3.0'

gem 'rails', '~> 8.0'
gem 'puma', '~> 6.4'
gem 'dotenv-rails', '~> 3.1'
gem 'jwt', '~> 2.9'
gem 'pg', '~> 1.5'

group :development, :test do
  gem 'rspec-rails', '~> 7.0'
  gem 'sqlite3', '~> 2.0'
end
