apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "23-slim.fullname" . }}
  labels:
    {{- include "23-slim.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "23-slim.selectorLabels" . | nindent 6 }}
