{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "19-aspnet-core.serviceAccountName" . }}
  labels:
    {{- include "19-aspnet-core.labels" . | nindent 4 }}
{{- end }}
