apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "18-ktor.fullname" . }}
  labels:
    {{- include "18-ktor.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "18-ktor.selectorLabels" . | nindent 6 }}
