apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "14-elysia.fullname" . }}
  labels:
    {{- include "14-elysia.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "14-elysia.selectorLabels" . | nindent 6 }}
