{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "23-laravel.serviceAccountName" . }}
  labels:
    {{- include "23-laravel.labels" . | nindent 4 }}
{{- end }}
