{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "17-spring-boot.serviceAccountName" . }}
  labels:
    {{- include "17-spring-boot.labels" . | nindent 4 }}
{{- end }}
