apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 22-rails
  namespace: argocd
spec:
  project: pipeline-platform
  source:
    repoURL: https://github.com/yarova-ca/pipeline-studio
    targetRevision: main
    path: services/22-rails/helm
    helm:
      valueFiles:
        - values.yaml
        - values.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
