{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "08-mf-rspack.serviceAccountName" . }}
  labels:
    {{- include "08-mf-rspack.labels" . | nindent 4 }}
{{- end }}
