{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "21-phoenix.serviceAccountName" . }}
  labels:
    {{- include "21-phoenix.labels" . | nindent 4 }}
{{- end }}
