apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "15-flask.fullname" . }}
  labels:
    {{- include "15-flask.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "15-flask.selectorLabels" . | nindent 6 }}
