apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "03-eleventy.fullname" . }}
  labels:
    {{- include "03-eleventy.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "03-eleventy.selectorLabels" . | nindent 6 }}
