replicaCount: 2
image:
  tag: "staging"

networkPolicy:
  enabled: true   # Staging mirrors prod — must test network isolation before prod
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
  hosts:
    - host: 14-express.staging.yarova.ca
      paths:
        - path: /
          pathType: Prefix
