replicaCount: 1

image:
  repository: "ghcr.io/yarova-ca/14-express"
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: "14-express"

serviceAccount:
  create: true
  name: "14-express"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: 14-express.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env: {}

envFrom: []

networkPolicy:
  enabled: false  # Enable in prod

livenessProbe:
  httpGet:
    path: /health/live
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/ready
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
