{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "29-graphql-yoga.serviceAccountName" . }}
  labels:
    {{- include "29-graphql-yoga.labels" . | nindent 4 }}
{{- end }}
