apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "16-gin.fullname" . }}
  labels:
    {{- include "16-gin.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "16-gin.selectorLabels" . | nindent 6 }}
