{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "16-chi.serviceAccountName" . }}
  labels:
    {{- include "16-chi.labels" . | nindent 4 }}
{{- end }}
