apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: prod/pipeline-studio/backstage
        property: github_token
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: prod/pipeline-studio/backstage
        property: auth_client_id
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: prod/pipeline-studio/backstage
        property: auth_client_secret
