{{- if ge (int .Values.replicaCount) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "07-nextjs-app-router.fullname" . }}
  labels:
    {{- include "07-nextjs-app-router.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "07-nextjs-app-router.selectorLabels" . | nindent 6 }}
{{- end }}
