{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "18-spring-boot-kotlin.serviceAccountName" . }}
  labels:
    {{- include "18-spring-boot-kotlin.labels" . | nindent 4 }}
{{- end }}
