apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - ${{ values.framework }}
    - backend
  annotations:
    github.com/project-slug: yarova-ca/${{ values.name }}
    backstage.io/techdocs-ref: url:https://github.com/yarova-ca/${{ values.name }}/tree/main
    backstage.io/kubernetes-label-selector: app=${{ values.name }}
spec:
  type: service
  lifecycle: production
  owner: group:platform-team
  system: pipeline-platform
  providesApis:
    - ${{ values.name }}-api
