{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "01-solid-start.serviceAccountName" . }}
  labels:
    {{- include "01-solid-start.labels" . | nindent 4 }}
{{- end }}
