{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "02-preact.serviceAccountName" . }}
  labels:
    {{- include "02-preact.labels" . | nindent 4 }}
{{- end }}
