{{- if ge (int .Values.replicaCount) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "26-ring.fullname" . }}
  labels:
    {{- include "26-ring.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "26-ring.selectorLabels" . | nindent 6 }}
{{- end }}
