{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "26-ring.serviceAccountName" . }}
  labels:
    {{- include "26-ring.labels" . | nindent 4 }}
{{- end }}
