apiVersion: apps/v1
kind: Deployment
metadata:
  name: 29-graphql-yoga
  labels:
    app: 29-graphql-yoga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 29-graphql-yoga
  template:
    metadata:
      labels:
        app: 29-graphql-yoga
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: 29-graphql-yoga
          image: ghcr.io/yarova-ca/29-graphql-yoga:latest
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 4000
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 4000
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
