apiVersion: apps/v1
kind: Deployment
metadata:
  name: 02-solidjs
  labels:
    app: 02-solidjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 02-solidjs
  template:
    metadata:
      labels:
        app: 02-solidjs
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: 02-solidjs
          image: ghcr.io/yarova-ca/02-solidjs:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
