apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "19-minimal-apis.fullname" . }}
  labels:
    {{- include "19-minimal-apis.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "19-minimal-apis.selectorLabels" . | nindent 6 }}
