replicaCount: 1

image:
  repository: "ghcr.io/yarova-ca/02-react"   # set in CI: ghcr.io/yarova-ca/02-react
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: "02-react"

serviceAccount:
  create: true
  name: "02-react"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: 02-react.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env: {}

envFrom: []

livenessProbe:
  httpGet:
    path: /health/live
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/ready
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5

networkPolicy:
  enabled: false
