{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "27-drogon.serviceAccountName" . }}
  labels:
    {{- include "27-drogon.labels" . | nindent 4 }}
{{- end }}
