apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
  - ../../base
images:
  - name: ghcr.io/yarova-ca/19-aspnet-core
    newTag: "dev"
patches:
  - target:
      kind: Deployment
      name: 19-aspnet-core
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
