{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "14-express.serviceAccountName" . }}
  labels:
    {{- include "14-express.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
